### ISSUE TITLE
adding map into a Stack 

### ISSUE THREAD

**Issue by shadman-sakib** [m0nac0/flutter-mapbox-gl#147] opened 2022-08-16 05:49 UTC
Is it possible to add MaplibreMap in a stack without without the other widgets in stack being overlayed by the map? 

 return Stack(
      children: <Widget>[
        _buildMap(context),
        _buildPin(),
       .....
      ],
    );
    
   The other widgets are positioned in the stack. When the map is loaded the other widgets are not visible.

**Comment by martyfuhry** [comment] 2022-08-16 17:55
Looks like a duplicate of #144

**Comment by m0nac0** [comment] 2022-08-20 14:52
Closing as a duplicate, please try again with the latest flutter master version. Feel free to reopen this issue, if you think this is actually a separate issue.

**Closed as completed by m0nac0** 2022-08-20 14:52 UTC
