### ISSUE TITLE
Adding overlay on map

### ISSUE THREAD

**Issue by noorbakerally** [m0nac0/flutter-mapbox-gl#144] opened 2022-08-07 09:34 UTC
I am trying to add a Flutter Overlay (using the Overlay Class) on the map but cannot,  The Overlay is going to be some buttons. If I remove the map widget and replace with a Container widget, the overlay can be seen. From what I'm understanding, it's not possible to add such an overlay on the map, is that the case?

For example, below is how the overlay is when I remove the map widget as the body and replace it with a Container:
```
Scaffold(
      body: Container(
        color: Colors.red,
      ),
    );
```
I have defined the overlay and it's added to the screen as shown below:

![Bottom](https://user-images.githubusercontent.com/1171706/183284367-95dad8f6-17a0-48ce-97bd-9c577ad47566.png)

However, if I replace the Container with a instance of the MapLibre Widget, I can no longer see the overlay:
```
Scaffold(
      body: MaplibreMap(
        initialCameraPosition: CameraPosition(
            target: LatLng(-33.86711, 151.1947171),
            zoom: 5
        ),
      ),
    );
```

![Map](https://user-images.githubusercontent.com/1171706/183284593-bba53321-ebe5-4abc-a4c3-a4582dbd2aa7.png)

If this is not possible using the native Flutter Overlay, is it possible to add a Widget to the MapLibre Widget itself at a fixed position, such as a Flutter Button?

**Comment by m0nac0** [comment] 2022-08-07 13:21
On what Flutter version are you and does this also happen with a `Stack`?

There were some issues caused by Flutter 3.0 (see e.g. https://github.com/flutter/flutter/issues/104158 and linked issues), but they should be resolved in the latest Flutter beta.

**Comment by noorbakerally** [comment] 2022-08-07 13:27
Flutter Version: Channel stable, 3.0.5

I haven't checked with stack but i'm checking right now, even dialogs are not shown. It seems as if it is being show behind the map

**Comment by noorbakerally** [comment] 2022-08-07 13:57
I have checked with Flutter Channel beta, 3.3.0-0.2.pre and it is working, 

Thanks @m0nac0  for the help

**Comment by m0nac0** [comment] 2022-08-07 15:48
Great to hear @noorbakerally.

**Closed as completed by m0nac0** 2022-08-07 15:48 UTC
