### ISSUE TITLE
`animateCamera` appears to be broken on web 

### ISSUE THREAD

**Issue by erik** [m0nac0/flutter-mapbox-gl#162] opened 2022-10-06 08:16 UTC
Hi, I noticed that calls to `animateCamera()` seemed to have no effect when running web builds, but the same call worked fine on iOS.

Here's what I was calling:

```dart
    mapController.animateCamera(CameraUpdate.newLatLng(coordinates));
```

After some debugging I traced it back to this change, which appears to have triggered a null dereference: https://github.com/m0nac0/flutter-maplibre-gl/commit/c3e941b03b574880eead1db87e360d74c7a1e1c8#diff-4666b03e54f2025da49b0f804d0eb4401b13c0e9599cf74089d5d6a4abf144d0

Specifically, the use of `.jsObject` appears to be in the wrong place, as `getProperty` returns a `null` for unspecified options. 

I put together a quick fix in a [fork], but I do wonder if this is really the right approach. Maybe the `CameraOptions` class should be updated to reflect the nullability of its members instead.

For now I'm just using my fork as a dependency override, but if you think it's the right fix I can open a PR.

[fork]: https://github.com/m0nac0/flutter-maplibre-gl/compare/main...erik:flutter-maplibre-gl:fix-animate-camera

**Comment by stefanschaller** [comment] 2023-06-15 12:00
It seems like that I have the same issue:

```
3main.dart.js:8078 Uncaught TypeError: Cannot read properties of undefined (reading 'get$jsObject')
    at main.dart.js:235136:26
    at _wrapJsFunctionForAsync_closure.$protected (main.dart.js:10936:15)
    at _wrapJsFunctionForAsync_closure.call$2 (main.dart.js:90469:12)
    at Object._asyncStartSync (main.dart.js:10900:20)
    at MaplibreMapController0.animateCamera$body$MaplibreMapController0 (main.dart.js:235159:16)
    at MaplibreMapController0.animateCamera$2$duration (main.dart.js:235113:19)
    at main.dart.js:232740:66
    at _wrapJsFunctionForAsync_closure.$protected (main.dart.js:10936:15)
    at _wrapJsFunctionForAsync_closure.call$2 (main.dart.js:90469:12)
    at Object._asyncStartSync (main.dart.js:10900:20)
```

with the following code: 

```
    final cameraUpdate = CameraUpdate.newLatLngZoom(location, 16.5);

    await controller.animateCamera(
      cameraUpdate,
      duration: const Duration(milliseconds: 2100),
    );
```

@mariusvn @m0nac0

**Comment by JulianBissekkou** [comment] 2023-06-15 12:01
@mariusvn or @m0nac0 
Can some of you provide feedback?

**Comment by mariusvn** [comment] 2023-06-15 12:45
Hello, I'll take a look this weekend if i have time

**Comment by stefanschaller** [comment] 2023-06-15 13:15
@mariusvn  The issue is just in the release mode and it doesn't matter if the duration is assigned or not 

```
    await controller.animateCamera(
      CameraUpdate.newLatLngZoom(location, 16.5),
      duration: const Duration(milliseconds: 2100),
    );
```

Also not working: (without the animation param)

`await controller.animateCamera(CameraUpdate.newLatLngZoom(location, 16.5));`


I also found out that `moveCamera` is working properly.

**Comment by JulianBissekkou** [comment] 2023-06-16 07:17
I can verify that the fix that was suggested by @erik worked and I moved it into a pull request that can be reviewed.
https://github.com/maplibre/flutter-maplibre-gl/pull/254

**Comment by JulianBissekkou** [comment] 2023-06-29 05:32
Closing this as #254 is now merged and tested :)

**Closed as completed by JulianBissekkou** 2023-06-29 05:32 UTC
